baseURL = "http://example.org/"
languageCode = 'en-us'
title = 'P&O Pharma'
theme = 'agnes'

[params]
	dateFormat = "Jan 2, 2023" 
	authorName = "P&O Pharma"
	google_analytics_id = "GA-"
	
[menu]
	[[menu.main]]
		Name = "Contact"
		URL = "#"
		weight = 1
	
	[[menu.main]]
		Name = "About us"
		URL = "#"
		weight = 2
	
	[[menu.main]]
		Name = "FAQ's"
		URL = "#"
		weight = 3
	
	[[menu.main]]
		Name = "Support"
		URL = "#"
		weight = 4
		
[params.social]
	TwitterURL = "https://twitter.com/"
	GoogleURL = "http://google.com"
	FacebookURL = "https://facebook.com/"
		
[params.content]
	LeadTitle = "Chào mừng đến P&O Pharma"
	LeadDescription = "Our landing page template works for all the devices, so you only have to setup it once, and get beautiful results forever."
	ButtonCaption = "Liên hệ công ty"
	ButtonURL = "https://zalo.me/0939115395"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Azipowder"
	FeatureDescription = "Bột pha hỗn dịch uống Azipowder 200mg/5ml trị Nhiễm khuẩn đường hô hấp dưới"
	FeatureImage = "images/azipowder.png"
	
[[params.feature]]
	FeatureTitle = "Desbebe"
	FeatureDescription = "Viêm mũi dị ứng theo mùa, viêm mũi dị ứng lâu năm, chứng mề đay tự phát mãn tính."
	FeatureImage = "images/desbebe.jpg"

[[params.feature]]
	FeatureTitle = "Racesec 10"
	FeatureDescription = " Điều trị triệu chứng tiêu chảy cấp "
	FeatureImage = "images/racesec10.jpg"
	
[[params.feature]]
	FeatureTitle = "Seamama"
	FeatureDescription = "Hỗ trợ giảm các triệu chứng khí huyết ứ trệ cho phụ nữ sau sinh"
	FeatureImage = "images/pnologo.png"

[[params.feature]]
	FeatureTitle = "Maviced"
	FeatureDescription = "Bổ sung Vitamin và khoáng chất cho phụ nữ mang thai và cho con bú"
	FeatureImage = "images/maviced.png"
[[params.feature]]
	FeatureTitle = "Zepilen"
	FeatureDescription = " Kháng sinh dự phòng trước và sau phẫu thuật."
	FeatureImage = "images/zepilen.png"
	
[[params.feature]]
	FeatureTitle = "Lematin"
	FeatureDescription = "Bổ sung Vitamin và khoáng chất cho phụ nữ mang thai và cho con bú"
	FeatureImage = "images/lematin.png"

[[params.feature]]
	FeatureTitle = "Budamed 400"
	FeatureDescription = "Điều trị triệu chứng cấp tính của đau bụng kinh nguyên phát"
	FeatureImage = "images/pnologo.png"

[[params.feature]]
	FeatureTitle = "Racesec 30"
	FeatureDescription = " Điều trị triệu chứng tiêu chảy cấp"
	FeatureImage = "images/racesec30.png"
[[params.feature]]
	FeatureTitle = "Fessomas vitamin D3+ K2 spray"
	FeatureDescription = " Điều trị triệu chứng tiêu chảy cấp"
	FeatureImage = "images/pnologo.png"